# Welcome to the server configuration file for Sparky

# What should sparky display as the server brand
brand = "sparky"

# What port should sparky listen on
port = 25565

# The text that should be displayed when pinging
motd = "Powered by <yellow>sparky</yellow>!"

# Amount of threads to use
threads = 4

# Regex to filter for usernames
username_format = "([a-zA-Z0-9_])*"

# Format of the chat messages
# Parameters: username, pmessage
chat_format = "%s: %s"

# Amount of ticks per second
ticks_per_second = 20

# Text shown when hovering the ping icon in the server list
ping_version_hover = "&c1.8.9"

# The difficulty of the world
difficulty = 1

# Maximum amount of players allowed on the server
max_players = 100

# The radius where chunks gets sent
render_distance = 16

# Messages configuration section
[messages]

# Shown when the default world is missing
missing_world = "<red>Missing a default world!</red>"

# Shown when the player is using a username that doesn't match the regex
invalid_username = "<red>The chosen username is invalid!</red>"