# Welcome to the server configuration file for Sparky

# What should sparky display as the server brand
brand = "sparky 1.0"

# What port should sparky listen on
port = 25565

# The text that should be displayed when pinging
motd = "Powered by <yellow>sparky</yellow>!"

# Amount of netty threads to use
netty_threads = 4

# Amount of ticks per second
ticks_per_second = 20

# Text shown when hovering the ping icon in the server list
ping_version_hover = "&c1.8.9"

# The difficulty of the world
difficulty = 1

# Maximum amount of players allowed on the server
max_players = 100

# The radius where chunks gets sent
render_distance = 16